{{- if include "ctaudit.managedLokiSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctaudit.lokiSecretName" . }}
  labels:
    {{- include "ctaudit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.loki.auth.token }}
  CTAUDIT_LOKI_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.loki.auth.user }}
  CTAUDIT_LOKI_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.loki.auth.password }}
  CTAUDIT_LOKI_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
